export const shows = [
  {
    title: "The last of us",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285128/bingeMovies/the-last-of-us_xmm6s8.jpg",
    year: 2023,
    category: "tv show",
    rating: "R",
    isTrending: true,
    genres: ["action", "adventure", "drama"],
    trailer: "https://www.youtube.com/watch?v=uLtkt8BonwM",
    score: 9.3,
    plot: "20 years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal heartbreaking journey as they both must traverse the U.S. and depend on each other for survival.",
  },
  {
    title: "Avatar: The way of the water",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285127/bingeMovies/avatar-the-way-of-the-water_jszjhb.jpg",
    year: 2022,
    category: "movie",
    rating: "PG-13",
    isTrending: true,
    genres: ["action", "adventure", "fantasy"],
    trailer: "https://www.youtube.com/watch?v=bDFKIs4v0B4",
    score: 7.8,
    plot: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
  },
  {
    title: "The Menu",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285128/bingeMovies/the-menu_wvu47j.jpg",
    year: 2022,
    category: "tv show",
    rating: "R",
    isTrending: true,
    genres: ["horror", "thriller"],
    trailer: "https://www.youtube.com/watch?v=C_uTkUGcHv4",
    score: 7.2,
    plot: "Expecting nothing less than the best of everything haute cuisine has to offer, a group of ultra-wealthy gastronomes with a demanding palate arrive at the Hawthorn: an exclusive culinary temple run by highly regarded gourmet chef Julian Slowik. And prepared for an exquisite multiple-course meal and the experience of a lifetime, obsessive epicurean Tyler and his unimpressed plus-one Margot enter the private minimalist restaurant.",
  },
  {
    title: "The white lotus",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285127/bingeMovies/the-white-lotus_fseldy.jpg",
    year: 2021,
    category: "tv show",
    rating: "R",
    isTrending: false,
    genres: ["comedy", "drama"],
    trailer: "https://www.youtube.com/watch?v=TGLq7_MonZ4",
    score: 7.9,
    plot: "An all-star cast heads to a resort to unleash their worst, most privileged impulses. The series is a sharp social satire following the exploits of various guests and employees of the fictional White Lotus resort chain, whose stay becomes affected by their various dysfunctions.",
  },
  {
    title: "Babylon",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285127/bingeMovies/babylon_w5xfrj.jpg",
    year: 2022,
    category: "movie",
    rating: "R",
    isTrending: false,
    genres: ["comedy", "drama", "history"],
    trailer: "https://www.youtube.com/watch?v=5muQK7CuFtY",
    score: 7.6,
    plot: "An original epic set in 1920s Los Angeles led by Brad Pitt, Margot Robbie and Diego Calva, with an ensemble cast including Jovan Adepo, Li Jun Li and Jean Smart. A tale of outsized ambition and outrageous excess, it traces the rise and fall of multiple characters during an era of unbridled decadence and depravity in early Hollywood.",
  },
  {
    title: "Everything Everywhere All at Once",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285128/bingeMovies/everything-everywhere-all-at-once_mjdhqx.jpg",
    year: 2022,
    category: "movie",
    rating: "R",
    isTrending: true,
    genres: ["action", "adventure", "comedy"],
    trailer: "https://www.youtube.com/watch?v=wxN1T1uxQ2g",
    score: 8,
    plot: "With her laundromat teetering on the brink of failure and her marriage to wimpy husband Waymond on the rocks, overworked Evelyn Wang struggles to cope with everything, including tattered relationships with her judgmental father Gong Gong and her daughter Joy. She must also brace herself for an unpleasant meeting with an impersonal bureaucrat: Deirdre, the shabbily-dressed IRS auditor. However, as the stern agent loses patience, an inexplicable multiverse rift becomes an eye-opening exploration of parallel realities. Will Evelyn jump down the rabbit hole? How many stars are in the universe? Can weary Evelyn fathom the irrepressible force of possibilities, tap into newfound powers, and prevent an evil entity from destroying the thin, countless layers of the unseen world?",
  },
  {
    title: "Wednesday",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285127/bingeMovies/wednesday_nkpu9t.jpg",
    year: 2022,
    category: "tv show",
    rating: "PG-13",
    isTrending: true,
    genres: ["comedy", "crime", "fantasy"],
    trailer: "https://www.youtube.com/watch?v=Di310WS8zLk",
    score: 8.2,
    plot: "A sleuthing, supernaturally infused mystery charting Wednesday Addams' years as a student at Nevermore Academy. Wednesday's attempts to master her emerging psychic ability, thwart a monstrous killing spree that has terrorized the local town, and solve the supernatural mystery that embroiled her parents 25 years ago - all while navigating her new and very tangled relationships at Nevermore.",
  },
  {
    title: "House of the Dragon",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285127/bingeMovies/house-of-the-dragon_rstxln.jpg",
    year: 2022,
    category: "tv show",
    rating: "R",
    isTrending: false,
    genres: ["action", "adventure", "drama"],
    trailer: "https://www.youtube.com/watch?v=DotnJ7tTA34",
    score: 8.5,
    plot: "The Targaryen dynasty is at the absolute apex of its power, with more than 10 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
  },
  {
    title: "Puss in Boots: The Last Wish",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285128/bingeMovies/puss-in-boots-last-wish_dm9zry.jpg",
    year: 2022,
    category: "movie",
    rating: "PG",
    isTrending: false,
    genres: ["animation", "adventure", "comedy"],
    trailer: "https://www.youtube.com/watch?v=RqrXhwS33yc",
    score: 7.9,
    plot: "Sadly, Puss in Boots, the undaunted Spanish lover and hero, is now down to the last of his nine lives, a decade after the events of El gato con botas (2011). And as if that weren't enough, the unstoppable bounty hunter known as The Big Bad Wolf is after him. To restore all of his precious lives and escape an inglorious fate, Puss must pluck up his courage to embark on a dangerous quest into the Dark Forest to find the legendary Wishing Star.",
  },
  {
    title: "The Whale",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285128/bingeMovies/the_whale_fxwo87.jpg",
    year: 2022,
    category: "movie",
    rating: "R",
    isTrending: false,
    genres: ["drama"],
    trailer: "https://www.youtube.com/watch?v=i8zQKSI6wGU",
    score: 8,
    plot: "A reclusive, morbidly obese English teacher attempts to reconnect with his estranged teenage daughter.",
  },
  {
    title: "Yellowstone",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285127/bingeMovies/yellowstone_ef6oxf.jpg",
    year: 2018,
    category: "tv show",
    rating: "R",
    isTrending: false,
    genres: ["drama", "western"],
    trailer: "https://www.youtube.com/watch?v=opYyuupyWmA",
    score: 8.7,
    plot: "Yellowstone follows the Dutton family, led by John Dutton, who controls the largest contiguous ranch in the United States, under constant attack by those it borders - land developers, an Indian reservation, and America's first National Park. It is an intense study of a violent world far from media scrutiny - where land grabs make developers billions, and politicians are bought and sold by the world's largest oil and lumber corporations. Where drinking water poisoned by fracking wells and unsolved murders are not news: they are a consequence of living in the new frontier. It is the best and worst of America seen through the eyes of a family that represents both.",
  },
  {
    title: "You People",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285127/bingeMovies/you-people_nzgc3k.jpg",
    year: 2023,
    category: "movie",
    rating: "R",
    isTrending: false,
    genres: ["comedy", "romance"],
    trailer: "https://www.youtube.com/watch?v=pCMHc-IFAB0",
    score: 5.6,
    plot: "Follows a new couple and their families, who find themselves examining modern love and family dynamics amidst clashing cultures, societal expectations and generational differences.",
  },
  {
    title: "Shrinking",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285128/bingeMovies/shrinking_pvm7lg.jpg",
    year: 2023,
    category: "tv show",
    rating: "R",
    isTrending: false,
    genres: ["comedy", "drama"],
    trailer: "https://www.youtube.com/watch?v=YjHfjQDWl1A",
    score: 7.7,
    plot: "Jimmy is struggling to grieve the loss of his wife while being a dad, friend, and therapist. He decides to try a new approach with everyone in his path: unfiltered, brutal honesty. Can he help himself by helping others? Will it bring him back into the light?",
  },
  {
    title: "Shotgun Wedding",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285128/bingeMovies/shotgun-wedding_ybl83k.jpg",
    year: 2022,
    category: "movie",
    rating: "R",
    isTrending: true,
    genres: ["action", "comedy", "romance"],
    trailer: "https://www.youtube.com/watch?v=qNVwRHQL8jw",
    score: 5.5,
    plot: "Darcy (Jennifer Lopez) and Tom (Josh Duhamel) gather their lovable but very opinionated families for the ultimate destination wedding, just as the couple begins to get cold feet. And if that wasn't enough of a threat to the celebration, suddenly everyone's lives are in danger when the entire party is taken hostage. \"'Til Death Do Us Part\" takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save their loved ones--if they don't kill each other first.",
  },
  {
    title: "Hunters",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285128/bingeMovies/hunters_cn3tfz.jpg",
    year: 2020,
    category: "tv show",
    rating: "R",
    isTrending: true,
    genres: ["crime", "drama", "mystery"],
    trailer: "https://www.youtube.com/watch?v=ZWTrNmMQCR8",
    score: 7.2,
    plot: "In 1977 New York City, a troubled young Jewish man bent on revenge is taken in by a secret group of Nazi hunters fighting a clandestine war against the cabal of high-ranking Nazi officials in hiding who work to create the Fourth Reich.",
  },
  {
    title: "Megan",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285128/bingeMovies/megan_lpfvu3.jpg",
    year: 2022,
    category: "movie",
    rating: "PG-13",
    isTrending: false,
    genres: ["terror", "science fiction", "suspense"],
    trailer: "https://www.youtube.com/watch?v=e_6JPqOCH3c",
    score: 6.5,
    plot: "When Gemma suddenly becomes the caretaker of her orphaned 8-year-old niece, Cady, Gemma's unsure and unprepared to be a parent. Under intense pressure at work, Gemma decides to pair her M3GAN prototype with Cady in an attempt to resolve both problems-a decision that will have unimaginable consequences.",
  },
  {
    title: "Jack Ryan",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285128/bingeMovies/jack-ryan_qjqhnr.jpg",
    year: 2018,
    category: "tv show",
    rating: "R",
    isTrending: true,
    genres: ["action", "drama", "suspense"],
    trailer: "https://www.youtube.com/watch?v=8j13uPb8pFg",
    score: 8,
    plot: "When CIA analyst Jack Ryan stumbles upon a suspicious series of bank transfers his search for answers pulls him from the safety of his desk job and catapults him into a deadly game of cat and mouse throughout Europe and the Middle East, with a rising terrorist figurehead preparing for a massive attack against the US and her allies.",
  },
  {
    title: "The Banshees of Inisherin",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285128/bingeMovies/banshees-of-inisherin_b0xnxj.jpg",
    year: 2022,
    category: "movie",
    rating: "R",
    isTrending: false,
    genres: ["comedy", "drama"],
    trailer: "https://www.youtube.com/watch?v=uRu3zLOJN2c",
    score: 7.8,
    plot: "Set on a remote island off the west coast of Ireland, THE BANSHEES OF INISHERIN follows lifelong friends Padraic (Colin Farrell) and Colm (Brendan Gleeson), who find themselves at an impasse when Colm unexpectedly puts an end to their friendship. A stunned Padraic, aided by his sister Siobhan (Kerry Condon) and troubled young islander Dominic (Barry Keoghan), endeavours to repair the relationship, refusing to take no for an answer. But Padraic's repeated efforts only strengthen his former friend's resolve and when Colm delivers a desperate ultimatum, events swiftly escalate, with shocking consequences.",
  },
  {
    title: "Vikings: Valhalla",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285127/bingeMovies/vikings-valhalla_llthfb.jpg",
    year: 2022,
    category: "tv show",
    rating: "R",
    isTrending: false,
    genres: ["action", "adventure", "drama"],
    trailer: "https://www.youtube.com/watch?v=0DZKZ0qktU4",
    score: 7.2,
    plot: 'Vikings: Valhalla" begins in the early 11th century and chronicles the legendary adventures of some of the most famous Vikings who ever lived: Leif Eriksson, Freydis Eriksdotter, Harald Hardrada, and the Norman King William the Conqueror. These men and women blaze a path as they fight for survival in the ever-changing, evolving world.',
  },
  {
    title: "The Pale Blue Eye",
    thumbnail:
      "https://res.cloudinary.com/alais29/image/upload/v1675285127/bingeMovies/the-pale-blue-eyes_tagkoh.jpg",
    year: 2022,
    category: "movie",
    rating: "R",
    isTrending: false,
    genres: ["crime", "terror", "mystery"],
    trailer: "https://www.youtube.com/watch?v=J7tpfLV4-TQ",
    score: 6.6,
    plot: "At West Point Academy in 1830, the calm of an October evening is shattered by the discovery of a young cadet's body swinging from a rope just off the parade grounds. An apparent suicide is not unheard of in a harsh regimen like West Point's, but the next morning, an even greater horror comes to light. Someone has stolen into the room where the body lay and removed the heart.",
  },
];
